Band.create(username: 'Band1', password: 'qpass', band_name: 'QOTSA', bio: 'We rock!')
Band.create(username: 'Band2', password: 'rpass', band_name: 'RHCP', bio: 'We also rock!')
Band.create(username: 'Band3', password: 'asdf', band_name: 'QOTSA', bio: 'We rock!')
Band.create(username: 'Band4', password: 'rpass', band_name: 'RHCP', bio: 'We also rock!')
Band.create(username: 'Band5', password: 'qpass', band_name: 'QOTSA', bio: 'We rock!')
Band.create(username: 'Band6', password: 'rpass', band_name: 'RHCP', bio: 'We also rock!')
Band.create(username: 'Band7', password: 'qpass', band_name: 'QOTSA', bio: 'We rock!')
Band.create(username: 'Band8', password: 'rpass', band_name: 'RHCP', bio: 'We also rock!')
Band.create(username: 'Band9', password: 'qpass', band_name: 'QOTSA', bio: 'We rock!')
Band.create(username: 'Band10', password: 'rpass', band_name: 'RHCP', bio: 'We also rock!')

Listener.create(username: 'Ollie', password: 'olliep', name: 'Olivier')
Listener.create(username: 'Jordan', password: 'jordanp', name: 'Jordan')

Favorite.create(band_id: 1, listener_id: 2)
Favorite.create(band_id: 2, listener_id: 1)
