Band.create(username: 'Band1', password: 'qpass', band_name: 'Band1', bio: 'We rock!')
Band.create(username: 'Band2', password: 'rpass', band_name: 'Band2', bio: 'We also rock!')
Band.create(username: 'Band3', password: 'asdf', band_name: 'Band3', bio: 'We rock!')
Band.create(username: 'Band4', password: 'rpass', band_name: 'Band4', bio: 'We also rock!')
Band.create(username: 'Band5', password: 'qpass', band_name: 'Band5', bio: 'We rock!')
Band.create(username: 'Band6', password: 'rpass', band_name: 'Band6', bio: 'We also rock!')
Band.create(username: 'Band7', password: 'qpass', band_name: 'Band7', bio: 'We rock!')
Band.create(username: 'Band8', password: 'rpass', band_name: 'Band8', bio: 'We also rock!')
Band.create(username: 'Band9', password: 'qpass', band_name: 'Band9', bio: 'We rock!')
Band.create(username: 'Band10', password: 'rpass', band_name: 'Band10', bio: 'We also rock!')

Listener.create(username: 'Ollie', password: 'olliep', name: 'Olivier')
Listener.create(username: 'Jordan', password: 'jordanp', name: 'Jordan')
