Band.create(username: 'Band1UserName', password: 'band1pw', band_name: 'Band1', bio: 'We rock!')
Band.create(username: 'Band2UserName', password: 'band2pw', band_name: 'Band2', bio: 'We also rock!')
Band.create(username: 'Band3UserName', password: 'band3pw', band_name: 'Band3', bio: 'We rock!')
Band.create(username: 'Band4UserName', password: 'band4pw', band_name: 'Band4', bio: 'We also rock!')
Band.create(username: 'Band5UserName', password: 'band5pw', band_name: 'Band5', bio: 'We rock!')
Band.create(username: 'Band6UserName', password: 'band6pw', band_name: 'Band6', bio: 'We also rock!')
Band.create(username: 'Band7UserName', password: 'band7pw', band_name: 'Band7', bio: 'We rock!')
Band.create(username: 'Band8UserName', password: 'band8pw', band_name: 'Band8', bio: 'We also rock!')
Band.create(username: 'Band9UserName', password: 'band9pw', band_name: 'Band9', bio: 'We rock!')
Band.create(username: 'Band10UserName', password: 'band10pw', band_name: 'Band10', bio: 'We also rock!')

Listener.create(username: 'Listener1UserName', password: 'listener1pw', name: 'Olivier')
Listener.create(username: 'Listener2UserName', password: 'listener2pw', name: 'Jordan')
Listener.create(username: 'Listener3UserName', password: 'listener3pw', name: 'Max')
Listener.create(username: 'Listener4UserName', password: 'listener4pw', name: 'Scoti')

Question.create(band_id: 1, listener_id: 1, question_response: 'Question 1', has_answered: false)
Question.create(band_id: 1, listener_id: 2, question_response: 'Question 2', has_answered: false)
Question.create(band_id: 2, listener_id: 3, question_response: 'Question 3', has_answered: false)
Question.create(band_id: 2, listener_id: 3, question_response: 'Question 4', has_answered: false)
Question.create(band_id: 2, listener_id: 5, question_response: 'Question 5', has_answered: false)
Question.create(band_id: 6, listener_id: 5, question_response: 'Question 6', has_answered: false)
Question.create(band_id: 6, listener_id: 6, question_response: 'Question 7', has_answered: false)
Question.create(band_id: 6, listener_id: 7, question_response: 'Question 8', has_answered: false)
Question.create(band_id: 6, listener_id: 8, question_response: 'Question 9', has_answered: false)
